services:
  litellm:
    volumes:
      - ./litellm/litellm.languse.yaml:/app/litellm/langfuse.yaml
    environment:
      - LANGFUSE_HOST=http://langfuse:3000
      - LANGFUSE_PUBLIC_KEY=${HARBOR_LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${HARBOR_LANGFUSE_SECRET_KEY}