services:
  parllama:
    container_name: ${HARBOR_CONTAINER_PREFIX}.parllama
    env_file:
      - ./.env
      - ./parllama/override.env
    build:
      context: ./parllama
      dockerfile: Dockerfile
    volumes:
      - ${HARBOR_PARLLAMA_CACHE}:/root/.local/share/parllama
    tty: true
    user: root
    networks:
      - harbor-network