services:
  moltbot:
    container_name: ${HARBOR_CONTAINER_PREFIX}.moltbot
    image: ${HARBOR_MOLTBOT_IMAGE}:${HARBOR_MOLTBOT_VERSION}
    build:
      context: ${HARBOR_MOLTBOT_GIT_REF}
      dockerfile: Dockerfile
      args:
        MOLTBOT_DOCKER_APT_PACKAGES: ${HARBOR_MOLTBOT_DOCKER_APT_PACKAGES}
    env_file:
      - ./.env
      - ./moltbot/override.env
    environment:
      - HOME=/home/node
      - TERM=xterm-256color
      - MOLTBOT_GATEWAY_TOKEN=${HARBOR_MOLTBOT_GATEWAY_TOKEN}
      - MOLTBOT_GATEWAY_BIND=${HARBOR_MOLTBOT_GATEWAY_BIND}
      - MOLTBOT_GATEWAY_PORT=${HARBOR_MOLTBOT_HOST_PORT}
      - MOLTBOT_BRIDGE_PORT=${HARBOR_MOLTBOT_BRIDGE_HOST_PORT}
      - HARBOR_MOLTBOT_AUTO_APPROVE_UI=${HARBOR_MOLTBOT_AUTO_APPROVE_UI}
      - CLAUDE_AI_SESSION_KEY=${HARBOR_MOLTBOT_CLAUDE_AI_SESSION_KEY}
      - CLAUDE_WEB_SESSION_KEY=${HARBOR_MOLTBOT_CLAUDE_WEB_SESSION_KEY}
      - CLAUDE_WEB_COOKIE=${HARBOR_MOLTBOT_CLAUDE_WEB_COOKIE}
    volumes:
      - ${HARBOR_MOLTBOT_CONFIG_DIR}:/home/node/.moltbot
      - ${HARBOR_MOLTBOT_WORKSPACE_DIR}:/home/node/molty
      - ./moltbot/entrypoint.sh:/entrypoint.sh
    ports:
      - ${HARBOR_MOLTBOT_HOST_PORT}:${HARBOR_MOLTBOT_HOST_PORT}
      - ${HARBOR_MOLTBOT_BRIDGE_HOST_PORT}:${HARBOR_MOLTBOT_BRIDGE_HOST_PORT}
    init: true
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - harbor-network
