services:
  onyx:
    image: nginx:1.25.5-alpine
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx
    env_file:
      - ./.env
      - ./onyx/override.env
    volumes:
      - ./onyx/nginx/app.conf.template:/etc/nginx/conf.d/app.conf.template:ro
      - ./onyx/nginx/run-nginx.sh:/docker-entrypoint-mount.sh:ro
    entrypoint: ["sh", "-c", "cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh"]
    environment:
      ONYX_BACKEND_API_HOST: onyx-api
      ONYX_WEB_SERVER_HOST: onyx-web
    depends_on:
      - onyx-api
      - onyx-web
    ports:
      - ${HARBOR_ONYX_HOST_PORT}:80
    networks:
      - harbor-network
    restart: unless-stopped

  onyx-web:
    image: onyxdotapp/onyx-web-server:${HARBOR_ONYX_VERSION}
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx.web
    env_file:
      - ./.env
      - ./onyx/override.env
    environment:
      INTERNAL_URL: http://onyx-api:8080
      NEXT_PUBLIC_DISABLE_STREAMING: ${HARBOR_ONYX_DISABLE_STREAMING:-false}
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      - onyx-api
    networks:
      - harbor-network
    restart: unless-stopped

  onyx-api:
    image: onyxdotapp/onyx-backend:${HARBOR_ONYX_VERSION}
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx.api
    command: >
      /bin/sh -c "
      alembic upgrade head &&
      echo 'Starting Onyx API Server' &&
      uvicorn onyx.main:app --host 0.0.0.0 --port 8080"
    env_file:
      - ./.env
      - ./onyx/override.env
    environment:
      AUTH_TYPE: ${HARBOR_ONYX_AUTH_TYPE:-disabled}
      POSTGRES_HOST: onyx-db
      POSTGRES_USER: ${HARBOR_ONYX_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${HARBOR_ONYX_DB_PASSWORD:-onyx}
      POSTGRES_DB: ${HARBOR_ONYX_DB_NAME:-onyx}
      VESPA_HOST: onyx-index
      REDIS_HOST: onyx-cache
      MODEL_SERVER_HOST: ${HARBOR_ONYX_MODEL_SERVER_HOST:-}
      MODEL_SERVER_PORT: ${HARBOR_ONYX_MODEL_SERVER_PORT:-11434}
      DISABLE_MODEL_SERVER: ${HARBOR_ONYX_DISABLE_MODEL_SERVER:-true}
      S3_ENDPOINT_URL: http://onyx-minio:9000
      S3_AWS_ACCESS_KEY_ID: ${HARBOR_ONYX_MINIO_USER:-minioadmin}
      S3_AWS_SECRET_ACCESS_KEY: ${HARBOR_ONYX_MINIO_PASSWORD:-minioadmin}
      DO_NOT_TRACK: "true"
      DANSWER_RUNNING_IN_DOCKER: "true"
      ENV_SEED_CONFIGURATION: '{"llms":[{"name":"Harbor Ollama","provider":"ollama_chat","api_base":"http://ollama:11434","default_model_name":"${HARBOR_ONYX_DEFAULT_MODEL:-llama3.2:3b}","fast_default_model_name":"${HARBOR_ONYX_FAST_MODEL:-llama3.2:3b}","is_public":true,"api_key_changed":true,"model_configurations":[]}]}'
    volumes:
      - ${HARBOR_ONYX_WORKSPACE}/api_logs:/var/log/onyx
    depends_on:
      onyx-db:
        condition: service_healthy
      onyx-index:
        condition: service_started
      onyx-cache:
        condition: service_started
      onyx-minio:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - harbor-network
    restart: unless-stopped

  onyx-background:
    image: onyxdotapp/onyx-backend:${HARBOR_ONYX_VERSION}
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx.background
    command: >
      /bin/sh -c "/app/scripts/supervisord_entrypoint.sh"
    env_file:
      - ./.env
      - ./onyx/override.env
    environment:
      USE_LIGHTWEIGHT_BACKGROUND_WORKER: "true"
      AUTH_TYPE: ${HARBOR_ONYX_AUTH_TYPE:-disabled}
      POSTGRES_HOST: onyx-db
      POSTGRES_USER: ${HARBOR_ONYX_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${HARBOR_ONYX_DB_PASSWORD:-onyx}
      POSTGRES_DB: ${HARBOR_ONYX_DB_NAME:-onyx}
      VESPA_HOST: onyx-index
      REDIS_HOST: onyx-cache
      MODEL_SERVER_HOST: ${HARBOR_ONYX_MODEL_SERVER_HOST:-}
      MODEL_SERVER_PORT: ${HARBOR_ONYX_MODEL_SERVER_PORT:-11434}
      INDEXING_MODEL_SERVER_HOST: ${HARBOR_ONYX_MODEL_SERVER_HOST:-}
      DISABLE_MODEL_SERVER: ${HARBOR_ONYX_DISABLE_MODEL_SERVER:-true}
      S3_ENDPOINT_URL: http://onyx-minio:9000
      S3_AWS_ACCESS_KEY_ID: ${HARBOR_ONYX_MINIO_USER:-minioadmin}
      S3_AWS_SECRET_ACCESS_KEY: ${HARBOR_ONYX_MINIO_PASSWORD:-minioadmin}
      DO_NOT_TRACK: "true"
      DANSWER_RUNNING_IN_DOCKER: "true"
      ENV_SEED_CONFIGURATION: '{"llms":[{"name":"Harbor Ollama","provider":"ollama_chat","api_base":"http://ollama:11434","default_model_name":"${HARBOR_ONYX_DEFAULT_MODEL:-llama3.2:3b}","fast_default_model_name":"${HARBOR_ONYX_FAST_MODEL:-llama3.2:3b}","is_public":true,"api_key_changed":true,"model_configurations":[]}]}'
    volumes:
      - ${HARBOR_ONYX_WORKSPACE}/background_logs:/var/log/onyx
    depends_on:
      onyx-db:
        condition: service_healthy
      onyx-index:
        condition: service_started
      onyx-cache:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - harbor-network
    restart: unless-stopped

  onyx-db:
    image: postgres:15.2-alpine
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx.db
    env_file:
      - ./.env
      - ./onyx/override.env
    environment:
      POSTGRES_USER: ${HARBOR_ONYX_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${HARBOR_ONYX_DB_PASSWORD:-onyx}
      POSTGRES_DB: ${HARBOR_ONYX_DB_NAME:-onyx}
    command: -c max_connections=250
    volumes:
      - ${HARBOR_ONYX_WORKSPACE}/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${HARBOR_ONYX_DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - harbor-network
    restart: unless-stopped

  onyx-cache:
    image: redis:7.4-alpine
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx.cache
    command: redis-server --save "" --appendonly no
    tmpfs:
      - /data
    networks:
      - harbor-network
    restart: unless-stopped

  onyx-index:
    image: vespaengine/vespa:${HARBOR_ONYX_VESPA_VERSION}
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx.index
    environment:
      VESPA_SKIP_UPGRADE_CHECK: "true"
    volumes:
      - ${HARBOR_ONYX_WORKSPACE}/vespa:/opt/vespa/var
    networks:
      - harbor-network
    restart: unless-stopped

  onyx-minio:
    image: minio/minio:${HARBOR_ONYX_MINIO_VERSION}
    container_name: ${HARBOR_CONTAINER_PREFIX}.onyx.minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${HARBOR_ONYX_MINIO_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${HARBOR_ONYX_MINIO_PASSWORD:-minioadmin}
    volumes:
      - ${HARBOR_ONYX_WORKSPACE}/minio:/data
    networks:
      - harbor-network
    restart: unless-stopped
