services:
  ollama:
    container_name: ${HARBOR_CONTAINER_PREFIX}.ollama
    env_file: ./.env
    volumes:
      - ${HARBOR_OLLAMA_CACHE}:/root/.ollama
      - ${HARBOR_HF_CACHE}:/root/.cache/huggingface
      - ${HARBOR_LLAMACPP_CACHE}:/root/.cache/llama.cpp
      - ${HARBOR_VLLM_CACHE}:/root/.cache/vllm
      - ./ollama/modelfiles:/modelfiles
    tty: true
    image: ollama/ollama:${HARBOR_OLLAMA_VERSION}
    ports:
      - ${HARBOR_OLLAMA_HOST_PORT}:11434
    networks:
      - harbor-network