services:
  fabric:
    container_name: ${HARBOR_CONTAINER_PREFIX}.fabric
    env_file:
      - ./.env
      - ./fabric/override.env
    image: ${HARBOR_FABRIC_IMAGE}:${HARBOR_FABRIC_VERSION}
    volumes:
      - ${HARBOR_FABRIC_CONFIG_PATH}:/root/.config/fabric
    networks:
      - harbor-network