services:
  boost:
    environment:
      - HARBOR_BOOST_OPENAI_URL_KTRANSFORMERS=${HARBOR_DEP_KTRANSFORMERS_INTERNAL_URL:-http://ktransformers:12456}/v1
      - HARBOR_BOOST_OPENAI_KEY_KTRANSFORMERS=sk-transformers