services:
  webui:
    image: ghcr.io/open-webui/open-webui:${HARBOR_WEBUI_VERSION}
    env_file:
      - ./.env
      - ./open-webui/override.env
    container_name: ${HARBOR_CONTAINER_PREFIX}.webui
    volumes:
      - ./open-webui:/app/backend/data
      - ./open-webui/start_webui.sh:/app/start_webui.sh
      - ./shared/json_config_merger.py:/app/json_config_merger.py
      - ./open-webui/configs/config.override.json:/app/configs/config.z.override.json
    entrypoint: ["/app/start_webui.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 10s
    ports:
      - ${HARBOR_WEBUI_HOST_PORT}:8080
    networks:
      - harbor-network
    environment:
      - WEBUI_NAME=${HARBOR_WEBUI_NAME}
      - WEBUI_SECRET_KEY=${HARBOR_WEBUI_SECRET}
      - GLOBAL_LOG_LEVEL=${HARBOR_WEBUI_LOG_LEVEL}