services:
  # Proxy to work around the secure cookies
  # and cors for localhost deployment
  perplexideez:
    container_name: ${HARBOR_CONTAINER_PREFIX}.perplexideez
    image: nginx:alpine
    ports:
      - ${HARBOR_PERPLEXIDEEZ_HOST_PORT}:80
    configs:
      - source: perplexideez_proxy_config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      perplexideez-service:
        condition: service_healthy
    networks:
      - harbor-network

  perplexideez-service:
    container_name: ${HARBOR_CONTAINER_PREFIX}.perplexideez-service
    image: ${HARBOR_PERPLEXIDEEZ_IMAGE}:${HARBOR_PERPLEXIDEEZ_VERSION}
    env_file:
      - ./.env
      - ./perplexideez/override.env
    healthcheck:
      # TODO:
      # https://github.com/brunostjohn/perplexideez/issues/12
      test: ["CMD", "true"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 10s
    depends_on:
      perplexideez-db:
        condition: service_healthy
      perplexideez-migrate:
        condition: service_completed_successfully
    networks:
      - harbor-network

  perplexideez-db:
    container_name: ${HARBOR_CONTAINER_PREFIX}.perplexideez-db
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./perplexideez/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d postgres -U postgres -h localhost"
      interval: 2s
      timeout: 60s
      retries: 5
    env_file:
      - ./.env
      - ./perplexideez/override.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - harbor-network

  perplexideez-migrate:
    container_name: ${HARBOR_CONTAINER_PREFIX}.perplexideez-migrate
    image: ${HARBOR_PERPLEXIDEEZ_MIGRATE_IMAGE}
    env_file:
      - ./.env
      - ./perplexideez/override.env
    depends_on:
      perplexideez-db:
        condition: service_healthy
    networks:
      - harbor-network
