services:
  llamaswap:
    container_name: ${HARBOR_CONTAINER_PREFIX}.llamaswap
    image: ${HARBOR_LLAMASWAP_IMAGE}:cpu
    ports:
      - ${HARBOR_LLAMASWAP_HOST_PORT}:8080
    env_file:
      - ./.env
      - llamaswap/override.env
    networks:
      - harbor-network
    volumes:
      - ${HARBOR_OLLAMA_CACHE}:/app/.ollama
      - ${HARBOR_HF_CACHE}:/app/.cache/huggingface
      - ${HARBOR_LLAMACPP_CACHE}:/app/.cache/llama.cpp
      - ${HARBOR_VLLM_CACHE}:/app/.cache/vllm
      - ./llamaswap/config.yaml:/app/config.yaml