services:
  mcpforge:
    container_name: ${HARBOR_CONTAINER_PREFIX}.mcpforge
    image: ${HARBOR_MCPFORGE_IMAGE}:${HARBOR_MCPFORGE_VERSION}
    ports:
      - ${HARBOR_MCPFORGE_HOST_PORT}:4444
    env_file:
      - ./.env
      - ./mcpforge/override.env
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - DATABASE_URL=${HARBOR_MCPFORGE_DATABASE_URL}
      - MCPGATEWAY_UI_ENABLED=true
      - MCPGATEWAY_ADMIN_API_ENABLED=true
      - JWT_SECRET_KEY=${HARBOR_MCPFORGE_JWT_SECRET}
      - JWT_AUDIENCE=${HARBOR_MCPFORGE_JWT_AUDIENCE}
      - JWT_ISSUER=${HARBOR_MCPFORGE_JWT_ISSUER}
      - BASIC_AUTH_USER=${HARBOR_MCPFORGE_BASIC_AUTH_USER}
      - BASIC_AUTH_PASSWORD=${HARBOR_MCPFORGE_BASIC_AUTH_PASSWORD}
      - AUTH_REQUIRED=${HARBOR_MCPFORGE_AUTH_REQUIRED}
      - PLATFORM_ADMIN_EMAIL=${HARBOR_MCPFORGE_ADMIN_EMAIL}
      - PLATFORM_ADMIN_PASSWORD=${HARBOR_MCPFORGE_ADMIN_PASSWORD}
      - PLATFORM_ADMIN_FULL_NAME=${HARBOR_MCPFORGE_ADMIN_FULL_NAME}
      - SECURE_COOKIES=false
    volumes:
      - ./mcpforge/data:/app/data
    networks:
      - harbor-network
