services:
  vllm:
    container_name: ${HARBOR_CONTAINER_PREFIX}.vllm
    env_file:
      - ./.env
      - ./vllm/override.env
    build:
      context: ./vllm
      dockerfile: Dockerfile
      args:
        HARBOR_VLLM_IMAGE: ${HARBOR_VLLM_IMAGE}
        HARBOR_VLLM_VERSION: ${HARBOR_VLLM_VERSION}
    ports:
      - ${HARBOR_VLLM_HOST_PORT}:8000
    ipc: host
    volumes:
      - ${HARBOR_HF_CACHE}:/root/.cache/huggingface
      - ${HARBOR_VLLM_CACHE}:/root/.cache/vllm
    command: >
      ${HARBOR_VLLM_MODEL_SPECIFIER}
      ${HARBOR_VLLM_EXTRA_ARGS}
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HARBOR_HF_TOKEN}
      - VLLM_ATTENTION_BACKEND=${HARBOR_VLLM_ATTENTION_BACKEND}
    networks:
      - harbor-network
