services:
  boost:
    container_name: ${HARBOR_CONTAINER_PREFIX}.boost
    build:
      context: ./boost
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./boost/override.env
    volumes:
      - ./boost/src:/app
      - ${HARBOR_OLLAMA_CACHE}:/root/.ollama
      - ${HARBOR_HF_CACHE}:/root/.cache/huggingface
      - ${HARBOR_LLAMACPP_CACHE}:/root/.cache/llama.cpp
      - ${HARBOR_VLLM_CACHE}:/root/.cache/vllm
    ports:
      - ${HARBOR_BOOST_HOST_PORT}:8000
    networks:
      - harbor-network
