services:
  opennotebook:
    container_name: ${HARBOR_CONTAINER_PREFIX}.opennotebook
    image: ${HARBOR_OPENNOTEBOOK_IMAGE}:${HARBOR_OPENNOTEBOOK_VERSION}
    ports:
      - "${HARBOR_OPENNOTEBOOK_HOST_PORT}:8502"
      - "${HARBOR_OPENNOTEBOOK_API_PORT}:5055"
    environment:
      - OPEN_URL=${HARBOR_OPENNOTEBOOK_OPEN_URL}
      - OPENAI_API_KEY=${HARBOR_OPENAI_KEY:-}
      - ANTHROPIC_API_KEY=${HARBOR_ANTHROPIC_KEY:-}
      - GOOGLE_API_KEY=${HARBOR_GOOGLE_KEY:-}
      - GROQ_API_KEY=${HARBOR_GROQ_KEY:-}
      - SURREAL_URL=${HARBOR_OPENNOTEBOOK_SURREAL_URL}
      - SURREAL_USER=${HARBOR_OPENNOTEBOOK_SURREAL_USER}
      - SURREAL_PASSWORD=${HARBOR_OPENNOTEBOOK_SURREAL_PASSWORD}
      - SURREAL_NAMESPACE=${HARBOR_OPENNOTEBOOK_SURREAL_NAMESPACE}
      - SURREAL_DATABASE=${HARBOR_OPENNOTEBOOK_SURREAL_DATABASE}
      - API_URL=${HARBOR_OPENNOTEBOOK_API_URL:-}
      - OPEN_NOTEBOOK_PASSWORD=${HARBOR_OPENNOTEBOOK_PASSWORD:-}
    volumes:
      - ${HARBOR_OPENNOTEBOOK_WORKSPACE}/data:/app/data
      - ${HARBOR_OPENNOTEBOOK_WORKSPACE}/db:/mydata
    env_file:
      - ./.env
      - ./opennotebook/override.env
    networks:
      - harbor-network
