services:
  speaches:
    image: ghcr.io/speaches-ai/speaches:${HARBOR_SPEACHES_VERSION}-cpu
    container_name: ${HARBOR_CONTAINER_PREFIX}.speaches
    env_file:
      - ./.env
      - ./speaches/override.env
    ports:
      - ${HARBOR_SPEACHES_HOST_PORT}:8000
    volumes:
      - ${HARBOR_OLLAMA_CACHE}:/home/ubuntu/.ollama
      - ${HARBOR_HF_CACHE}:/home/ubuntu/.cache/huggingface
      - ${HARBOR_LLAMACPP_CACHE}:/home/ubuntu/.cache/llama.cpp
      - ${HARBOR_VLLM_CACHE}:/home/ubuntu/.cache/vllm
    networks:
      - harbor-network

  speaches-init:
    # Same image as used for the routines
    # for minimal overhead
    image: denoland/deno:distroless
    container_name: ${HARBOR_CONTAINER_PREFIX}.speaches-init
    depends_on:
      speaches:
        condition: service_started
    env_file:
      - ./.env
      - ./speaches/override.env
    volumes:
      - ./speaches/init_entrypoint.ts:/init_entrypoint.ts
    entrypoint: deno run -A init_entrypoint.ts
    networks:
      - harbor-network