services:
  tgi:
    container_name: ${HARBOR_CONTAINER_PREFIX}.tgi
    env_file: ./.env
    image: ghcr.io/huggingface/text-generation-inference:2.2.0
    command: ${HARBOR_TGI_MODEL_SPECIFIER} ${HARBOR_TGI_EXTRA_ARGS}
    ports:
      - ${HARBOR_TGI_HOST_PORT}:80
    volumes:
      - ${HARBOR_HF_CACHE}/hub:/data
    environment:
      - PORT=80
      - HOSTNAME=0.0.0.0
      - HF_TOKEN=${HARBOR_HF_TOKEN}
    networks:
      - harbor-network
