services:
  llamacpp:
    image: ${HARBOR_LLAMACPP_IMAGE}:server-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]