services:
  opencode:
    container_name: ${HARBOR_CONTAINER_PREFIX}.opencode
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/av/tools:latest
        RUN curl -fsSL https://opencode.ai/install | bash && \
            ln -s /root/.opencode/bin/opencode /usr/local/bin/opencode
    command: ["opencode", "serve", "--hostname=0.0.0.0", "--port=4096"]
    env_file:
      - ./.env
      - ./opencode/override.env
    environment:
      - OPENCODE_CONFIG_DIR=/root/.config/opencode
      - OPENCODE_SERVER_USERNAME=${HARBOR_OPENCODE_USERNAME}
      - OPENCODE_SERVER_PASSWORD=${HARBOR_OPENCODE_PASSWORD}
    ports:
      - "${HARBOR_OPENCODE_HOST_PORT}:4096"
    volumes:
      - ${HARBOR_OPENCODE_DATA}:/root/.local/share/opencode
      - ${HARBOR_OPENCODE_CONFIG}:/root/.config/opencode
    working_dir: /root
    networks:
      - harbor-network
