services:
  webui:
    volumes:
      - ./open-webui/configs/config.searxng.json:/app/configs/config.searxng.json
    environment:
      - SEARXNG_QUERY_URL=${HARBOR_SEARXNG_INTERNAL_URL}/search?q=<query>
