services:
  ollama:
    devices:
      - /dev/kfd
      - /dev/dri
    image: ${HARBOR_OLLAMA_IMAGE}:rocm

  ollama-init:
    devices:
      - /dev/kfd
      - /dev/dri
    image: ${HARBOR_OLLAMA_IMAGE}:rocm
