services:
  oterm:
    container_name: ${HARBOR_CONTAINER_PREFIX}.oterm
    build:
      context: ./services/oterm
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./services/oterm/override.env
    networks:
      - harbor-network
    volumes:
      - ${HARBOR_OTERM_WORKSPACE}:/root/.local/share/oterm
