services:
  khoj:
    container_name: ${HARBOR_CONTAINER_PREFIX}.khoj
    image: ${HARBOR_KHOJ_IMAGE}:${HARBOR_KHOJ_VERSION}
    depends_on:
      khoj-db:
        condition: service_healthy
    env_file:
      - ./.env
      - ./services/khoj/override.env
    ports:
      - ${HARBOR_KHOJ_HOST_PORT}:42110
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${HARBOR_KHOJ_WORKSPACE}/config:/root/.khoj/
      - ${HARBOR_KHOJ_WORKSPACE}/models:/root/.cache/torch/sentence_transformers
      - ${HARBOR_KHOJ_WORKSPACE}/huggingface:/root/.cache/huggingface
    environment:
      - POSTGRES_DB=${HARBOR_KHOJ_DB_NAME}
      - POSTGRES_USER=${HARBOR_KHOJ_DB_USER}
      - POSTGRES_PASSWORD=${HARBOR_KHOJ_DB_PASSWORD}
      - POSTGRES_HOST=khoj-db
      - POSTGRES_PORT=5432
      - KHOJ_DJANGO_SECRET_KEY=${HARBOR_KHOJ_DJANGO_SECRET_KEY}
      - KHOJ_DEBUG=${HARBOR_KHOJ_DEBUG}
      - KHOJ_ADMIN_EMAIL=${HARBOR_KHOJ_ADMIN_EMAIL}
      - KHOJ_ADMIN_PASSWORD=${HARBOR_KHOJ_ADMIN_PASSWORD}
      - KHOJ_TELEMETRY_DISABLE=${HARBOR_KHOJ_TELEMETRY_DISABLE}
    command: --host="0.0.0.0" --port=42110 -vv --anonymous-mode --non-interactive
    networks:
      - harbor-network

  khoj-db:
    container_name: ${HARBOR_CONTAINER_PREFIX}.khoj-db
    image: ${HARBOR_KHOJ_DB_IMAGE}:${HARBOR_KHOJ_DB_VERSION}
    env_file:
      - ./.env
      - ./services/khoj/override.env
    environment:
      - POSTGRES_USER=${HARBOR_KHOJ_DB_USER}
      - POSTGRES_PASSWORD=${HARBOR_KHOJ_DB_PASSWORD}
      - POSTGRES_DB=${HARBOR_KHOJ_DB_NAME}
    volumes:
      - ${HARBOR_KHOJ_WORKSPACE}/db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${HARBOR_KHOJ_DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - harbor-network
