services:
  openterminal:
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=${HARBOR_OLLAMA_INTERNAL_URL}
      - HARBOR_OLLAMA_URL=${HARBOR_OLLAMA_INTERNAL_URL}
      - HARBOR_OLLAMA_OPENAI_URL=${HARBOR_OLLAMA_INTERNAL_URL}/v1
      - HARBOR_OLLAMA_DEFAULT_MODELS=${HARBOR_OLLAMA_DEFAULT_MODELS}
      - HARBOR_OLLAMA_CONTEXT_LENGTH=${HARBOR_OLLAMA_CONTEXT_LENGTH}
