services:
  gptme:
    container_name: ${HARBOR_CONTAINER_PREFIX}.gptme
    build:
      context: ./services/gptme
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./services/gptme/override.env
    volumes:
      - ./services/gptme/config.toml:/root/.config/gptme/config.toml
    networks:
      - harbor-network
