services:
  npcsh:
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - NPCSH_CHAT_MODEL=${HARBOR_NPCSH_OLLAMA_MODEL}
      - NPCSH_CHAT_PROVIDER=ollama
      - NPCSH_VISION_MODEL=${HARBOR_NPCSH_OLLAMA_VISION_MODEL}
      - NPCSH_VISION_PROVIDER=ollama
      - NPCSH_EMBEDDING_MODEL=${HARBOR_NPCSH_OLLAMA_EMBEDDING_MODEL}
      - NPCSH_EMBEDDING_PROVIDER=ollama
      - NPCSH_REASONING_MODEL=${HARBOR_NPCSH_OLLAMA_REASONING_MODEL}
      - NPCSH_REASONING_PROVIDER=ollama
      - OLLAMA_HOST=${HARBOR_OLLAMA_INTERNAL_URL}
