services:
  lmdeploy:
    image: openmmlab/lmdeploy:${HARBOR_LMDEPLOY_VERSION}
    container_name: ${HARBOR_CONTAINER_PREFIX}.lmdeploy
    env_file:
      - ./.env
      - ./services/lmdeploy/override.env
    volumes:
      - ${HARBOR_HF_CACHE:-./services/lmdeploy/.hf-cache}:/root/.cache/huggingface
    ports:
      - ${HARBOR_LMDEPLOY_HOST_PORT}:23333
    ipc: host
    environment:
      - HF_TOKEN=${HARBOR_HF_TOKEN}
    command: lmdeploy serve api_server ${HARBOR_LMDEPLOY_MODEL} ${HARBOR_LMDEPLOY_EXTRA_ARGS}
    networks:
      - harbor-network