services:
  nexa:
    build:
      # This is a CUDA-enabled override for the base
      # image that is CPU-only
      args:
        - HARBOR_NEXA_IMAGE=nvidia/cuda:12.6.3-base-ubuntu24.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]