services:
  litlytics:
    container_name: ${HARBOR_CONTAINER_PREFIX}.litlytics
    env_file:
      - ./.env
      - ./services/litlytics/override.env
    image: ghcr.io/yamalight/litlytics:${HARBOR_LITLYTICS_VERSION}
    ports:
      - ${HARBOR_LITLYTICS_HOST_PORT}:3000
    networks:
      - harbor-network
