services:
  nexa:
    container_name: ${HARBOR_CONTAINER_PREFIX}.nexa
    build:
      context: ./services/nexa
      dockerfile: Dockerfile
      # This can (and will) be overridden by .x.nvidia file
      args:
        - HARBOR_NEXA_IMAGE=ubuntu:24.04
        - HARBOR_NEXA_VERSION=${HARBOR_NEXA_VERSION}
    ports:
      - ${HARBOR_NEXA_HOST_PORT}:8000
    networks:
      - harbor-network
    volumes:
      - ${HARBOR_NEXA_CACHE}:/root/.cache/nexa.ai
    env_file:
      - ./.env
      - ./services/nexa/override.env
    command: serve
