services:
  bifrost:
    container_name: ${HARBOR_CONTAINER_PREFIX}.bifrost
    image: ${HARBOR_BIFROST_IMAGE}:${HARBOR_BIFROST_VERSION}
    env_file:
      - ./.env
      - ./services/bifrost/override.env
    environment:
      APP_HOST: 0.0.0.0
      APP_DIR: /app/data
    ports:
      - ${HARBOR_BIFROST_HOST_PORT}:8080
    volumes:
      - ${HARBOR_BIFROST_WORKSPACE}:/app/data
      - ./services/bifrost/config:/app/config
    networks:
      - harbor-network
