services:
  solo:
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              capabilities: [gpu]
              device_ids:
              - nvidia.com/gpu=all
