FROM denoland/deno:alpine-2.5.3

USER root

RUN apk add --no-cache \
    bash \
    coreutils \
    curl \
    docker-cli \
    docker-cli-compose \
    git \
    jq \
    openssh-client \
    procps
