@host = http://localhost:33831

###

GET {{host}}/v1/models

###

POST {{host}}/v1/chat/completions
Content-Type: application/json

{
  "model": "any",
  "messages": [
    {
        "role": "system",
        "content": "You are a helpful assistant."
    },
    {
        "role": "user",
        "content": "Wno invented Rubiks Cube?"
    }
  ],
  "max_tokens": 60
}