@host = http://localhost:33951

###

curl {{host}}/health

###

curl {{host}}/docs

###

GET {{host}}/v1/models

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer EMPTY

{
  "model": "microsoft/Phi-3.5-mini-instruct",
  "messages": [
    {
        "role": "system",
        "content": "You are Mistral.rs, an AI assistant."
    },
    {
        "role": "user",
        "content": "Write a story about Rust error handling."
    }
  ],
  "stream": false
}

###

curl {{host}}/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer EMPTY" \
  -d '{
    "model": "",
    "messages": [
      {
          "role": "user",
          "content": "Write a story about Rust error handling."
      }
    ]
  }'