ARG HARBOR_CHATNIO_IMAGE=programzmh/chatnio
ARG HARBOR_CHATNIO_VERSION=latest

FROM ${HARBOR_CHATNIO_IMAGE}:${HARBOR_CHATNIO_VERSION}

# Python needed for config merging
RUN apk add python3 py3-pip py3-yaml