@host=http://localhost:{{HARBOR_AGENT_HOST_PORT}}

###

GET {{host}}

###

GET {{host}}/health

###

GET {{host}}/v1/models

###

POST {{host}}/v1/chat/completions
Authorization: Bearer {{HARBOR_AGENT_API_KEY}}

{
  "model": "any",
  "messages": [{
    "role": "user",
    "content": "How much do I need to earn to buy an average house in Poland?"
  }],
  "stream": false
}