@host = http://localhost:34131

###

GET {{host}}/health

###

GET {{host}}/v1/models

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer sk-boost

{
  "model": "klmbr-llama3.1:8b",
  "format": "json",
  "response_format": {
    "type": "json_object"
  },
  "messages": [
    {"role": "user", "content": "Suggest me a random color"}
  ],
  "temperature": 0
}

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: sk-boost

{
  "model": "klmbr-llama3.1:8b",
  "messages": [
    {"role": "user", "content": "Suggest me a random color"}
  ],
  "temperature": 0,
  "max_tokens": 20,
  "stream": true
}

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: sk-fake

{
  "model": "llama3.1:8b",
  "messages": [
    {"role": "user", "content": "Bobby was born in Paris. How old is Bobby?"}
  ],
  "temperature": 0,
  "stream": false
}

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: sk-fake

{
  "model": "rcn-llama3.1:8b",
  "messages": [
    {"role": "user", "content": "Bobby was born in Paris. How old is Bobby?"}
  ],
  "temperature": 0,
  "stream": false
}

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: sk-fake

{
  "model": "g1-llama3.1:8b",
  "messages": [
    {"role": "user", "content": "Bobby was born in Paris. How old is Bobby?"}
  ],
  "temperature": 0,
  "stream": false
}

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: sk-fake

{
  "model": "rcn-llama3.1:8b",
  "messages": [
    {"role": "user", "content": "3.11 or 3.9 which number is larger?"}
  ],
  "temperature": 0,
  "stream": false
}

###

POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: sk-boost

{
  "model": "example-llama3.1:8b",
  "messages": [
    {"role": "user", "content": "Boost?"}
  ],
  "temperature": 0,
  "stream": false
}