@host = http://localhost:34121

###

curl {{host}}/v1/models

###

curl {{host}}/v1/chat/completions -H 'Content-Type: application/json' -H "Authorization: Bearer sk-fake" -d '{
  "model": "anything",
  "messages": [
    {
      "role": "user",
      "content": "Bobby was born in Paris. How old is Bobby?"
    }
  ],
  "max_tokens": 30
}'