@host = http://localhost:33841
@apiKey = sk-litellm

###

curl {{host}}/models -H 'Authorization: Bearer {{apiKey}}'

###

curl {{host}}/v1/completions -X POST -H "Content-Type: application/json" -H 'Authorization: Bearer {{apiKey}}' -d '{
  "model": "tgi",
  "prompt": "Once upon a time",
  "max_tokens": 50
}'

###

curl {{host}}/v1/chat/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer {{apiKey}}' -d '{
  "model": "tgi",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Who are you?"
    }
  ],
  "max_tokens": 64
}'

###

curl {{host}}/v1/chat/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer {{apiKey}}' -d '{
  "model": "tgi",
  "messages": [
    {
      "role": "user",
      "content": "Who are you?"
    }
  ],
  "max_tokens": 64
}'

###

curl {{host}}/v1/chat/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer {{apiKey}}' -d '{
  "model": "vllm",
  "messages": [
    {
      "role": "user",
      "content": "Who are you?"
    }
  ],
  "max_tokens": 64
}'

###

curl {{host}}/health  -H 'Authorization: Bearer {{apiKey}}'