@host = http://localhost:33931
@apiKey = adk-tabbyapi


###

curl {{host}}/v1/models -H "Authorization: Bearer {{apiKey}}"

###

curl {{host}}/v1/model -H "Authorization: Bearer {{apiKey}}"

###

curl {{host}}/v1/model/list -H "Authorization: Bearer {{apiKey}}"

###

curl {{host}}/v1/templates -H "Authorization: Bearer {{apiKey}}"

###

curl {{host}}/v1/model/load -H "Content-Type: application/json" -H "Authorization: Bearer {{apiKey}}" -d '{
  "name": "/models/hf/Annuvin_gemma-2-2b-it-abliterated-4.0bpw-exl2"
}'

###


curl {{host}}/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer {{apiKey}}" -d '{
  "model": "/models/hf/Annuvin_gemma-2-2b-it-abliterated-4.0bpw-exl2",
  "messages": [
    {
        "role": "user",
        "content": "How to eat cake?"
    }
  ],
  "max_tokens": 60
}'

###

curl {{host}}/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer {{apiKey}}" -d '{
  "model": "gguf",
  "messages": [
    {
        "role": "user",
        "content": "How to eat cake?"
    }
  ],
  "max_tokens": 60
}'