ARG HARBOR_TENSORTRUTH_IMAGE=ljubobratovicrelja/tensor-truth
ARG HARBOR_TENSORTRUTH_VERSION=latest

FROM ${HARBOR_TENSORTRUTH_IMAGE}:${HARBOR_TENSORTRUTH_VERSION}

RUN pip install tensor-truth[docs,utils,papers]
